version: '3.8'

services:
  image-search:
    build: .
    container_name: image-search-service
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      # 如果需要持久化数据，可以挂载卷
      # - ./data:/app/data
      - ./logs:/app/logs 